### ISSUE TITLE
Running ccslint on codeclimate CLI crashes oddly

### ISSUE THREAD

**Issue by jhmilan** [codeclimate/codeclimate-csslint#2]
It is being impossible to me running csslint with codeclimate.

### setup
This is my local setup

* Mac OS X 10.10.3 (Yosemite)
* boot2docker 1.7.0
* codeclimate CLI 0.0.8 (installed the brew package)
* bash 4.3 (this is not important it worked exactly the same with 3.2 but I had to upgrade it by other reasons)

### codeclimate config

This is my .codeclimate.yml file

```
---
engines:
  phpcodesniffer:
    enabled: false
  coffeelint:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false
ratings:
  paths:
  - "**.php"
  - "**.js"
  - "**.css"
exclude_paths:
- "node_modules/**/*"
- "vendor/**/*"
- "etc/**/*"
- ".vagrant/**/*"
```

I run `composer analyze` and this is the result:

```
 codeclimate analyze
Starting analysis
Running csslint: \Error deleting container: Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
An error occurred trying to connect: Post https://192.168.59.103:2376/v1.19/containers/acbef0423c3c1cdd9aaa07fe2de1d47b3f052eb8991e0a443e07b8dfa95944bb/wait: EOF

```

After that the only possible solution is `boot2docker restart`. Other engines (phpcodesniffer) works. Any help?
