### ISSUE TITLE
Strange alphabetical sorting rules

### ISSUE THREAD

**Issue by zeird** [codeclimate/codeclimate-csslint#24]
In [this file](https://codeclimate.com/github/zeird/godville-ui-plus/source/forum.css) the engine says `Rule doesn't have all its properties in alphabetical ordered.` regarding this chunk of css:

    40% {
        -webkit-transform: matrix(1, 0, 0, 1, 0,-1);
        opacity: 1;
        transform: matrix(1, 0, 0, 1, 0,-1);
    }

But css-rules in that chunk are properly alphabetical ordered. I guess the engine ignores initial hyphen in `-webkit-transform` rule and tries to compare `webkit-transform` with `transform`? But prefixed css-rules should always be before the same non-prefixed.

So, is it a bug?

**Comment by pbrisbin** [comment]
I believe it's dropping vendor prefixes when considering sorting.

Therefore, the rule is triggering because you have `(-webkit-)transform` before `opacity`. I reproduced locally, and the issue went away when I change things to

```css
40% {
    opacity: 1;
    -webkit-transform: matrix(1, 0, 0, 1, 0,-1);
            transform: matrix(1, 0, 0, 1, 0,-1);
}
```

(I also used some conventional indentation here, though that's not required to address the sorting issue.)

Closing as not a bug, please re-open if you feel differently.
