### ISSUE TITLE
Where to take list of rules & how to disable particular rules

### ISSUE THREAD

**Issue by keepitsimple** [codeclimate/codeclimate-csslint#31]
Hi,

We want to disable IE6-IE7 compatibility rules 

I added into .codeclimate.yml the following params
```  
csslint:
    enabled: true
    checks:
      Compatibility:
        enabled: false
```

Is it right?

**Comment by wfleming** [comment]
Compatability is csslint's internal category for rules, but not a rule name itself. Code Climate's engine emits the specific rule name, so you need to exclude [each rule in that category](https://github.com/CSSLint/csslint/wiki/Rules#compatibility) specifically. So your config would need to include:

```yaml
csslint:
  enabled: true
    checks: 
      adjoining-classes:
        enabled: false
      box-sizing:
        enabled: false
      compatible-vendor-prefixes:
        enabled: false
      gradients:
        enabled: false
      text-indent:
        enabled: false
      vendor-prefix:
        enabled: false
      fallback-colors:
        enabled: false
      star-property-hack:
        enabled: false
      underscore-property-hack:
        enabled: false
      bulletproof-font-face:
        enabled: false
```

Hope that helps, @keepitsimple. If you're using https://codeclimate.com for your analysis, [our docs site](https://docs.codeclimate.com/docs/disabling-individual-checks) has some more information on how the site can help with excluding checks.
