### ISSUE TITLE
.csslintrc not working when it's in a directory

### ISSUE THREAD

**Issue by JoryHogeveen** [codeclimate/codeclimate-csslint#38]
ESLint allows a custom location for the config file:
```yml
  eslint:
    enabled: true
    config:
      config: FOLDER/.eslintrc
```

It seems CSSLint doesn't support this:
```yml
  csslint:
    enabled: true
    config:
      config: FOLDER/.csslintrc
```
It only works when the `.csslintrc` is in the root directory.
Do I need to change it or is it just not supported?
